### PR TITLE
.env support

### PR DESCRIPTION
**Pull request by Middlepepper**
First attempt at this so I might have done a clunky way. Thought I would add in the .env support in a  to make it easier to maintain.

Change Log
- Added from dotenv to load .env files.
- Added Values and .env file to repository.

### CODE REVIEW

**Review by fallenbagel — APPROVED** [review]
Thanks for the PR! 😄
Looks good to me!

Although, there are some changes i want to make. Change all jellyseerr to seerr as this script also is for overseerr + add in seerr url (I can push the commits tonight if you don't mind c:)

**Comment by Middlepepper** [comment]
Yeah that's no problem, sorry for the delay time-zones are fun like that! I'm new to how git works so I think I shouldn't make any changes ones it approved right?

**Comment by fallenbagel** [comment]
> Yeah that's no problem, sorry for the delay time-zones are fun like that! I'm new to how git works so I think I shouldn't make any changes ones it approved right?

You could make changes even after approved c:
If you could make the changes I mentioned that'd be wonderful! As I have not had time yet to since I've been a bit busy this month

**Comment by Middlepepper** [comment]
Alright I push through some more changed on this branch.

- Added support for BaseURL
- Updated some Printed messages.
- Update .env vars

**Review by fallenbagel — APPROVED** [review]
Thanks so much!

**Pull request merged**
